### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by vineyardbovines** [andrewlitt/react-nhl-client#1]
Hey @andrewlitt! I stumbled across your app here while trying to find if anyone has come up with an implementation for plotting goals on a rink SVG/image. Your implementation is great!

Your project doesn't have a license on it, so I wanted to ask if I could fork your goal plotting code? I'll include a link to your project in mine both in an inline comment and in the README as reference points. Thanks in advance, great stuff here!

**Comment by andrewlitt** [comment]
Hey Sara,

Absolutely! I guess I overlooked licensing, given I never thought someone would want the code... but go for it - glad to help. 

The plot and the legend are all contained within the RinkChart.js component. The 'rink' itself is just CSS putting a background image on a recharts graph.

The main data passed to the component is the 'allPlays' part of the response from the NHL API. My intermediate API for cutting down the response was really more for learning than practicality, but you can use it here: https://react-nhl-server.now.sh/game/{game-id-here}

I'll look to add comments to the component to make your life easier, as the getCoords function does a number of things which may seem confusing.

Lemme know if you have any questions! Happy to help.

**Comment by vineyardbovines** [comment]
Thanks so much! Great stuff. I also have an intermediary to their API, it's not the friendliest thing ever 😄 I'll let you know if I have any more questions! 

If you're interested, I'll be posting to [this repo](https://github.com/gretzky/nhl-api) once I get some more things going.
